<?php
/**
 * Templates200ResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Mediamask
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mediamask API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mediamask\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * Templates200ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Templates200Response
 * @package     Mediamask
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class Templates200ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Templates200Response"
     */
    public function testTemplates200Response()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
