<?php
/**
 * MediamaskApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Mediamask
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mediamask API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Mediamask\Test\Api;

use \Mediamask\Configuration;
use \Mediamask\ApiException;
use \Mediamask\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MediamaskApiTest Class Doc Comment
 *
 * @category Class
 * @package  Mediamask
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MediamaskApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for renderImage
     *
     * Render a new image.
     *
     */
    public function testRenderImage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templates
     *
     * Get all tempaltes.
     *
     */
    public function testTemplates()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
